{{- if and (not .Values.existingConfigMap) .Values.config.externalUrl .Values.config.upstreamTemplate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jwks-proxy.fullname" . }}
  labels:
    {{- include "jwks-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    listen: {{ .Values.config.listen | quote }}
    external_url: {{ required "config.externalUrl is required" .Values.config.externalUrl | quote }}
    upstream_template: {{ required "config.upstreamTemplate is required" .Values.config.upstreamTemplate | quote }}
    cache_ttl_seconds: {{ .Values.config.cacheTtlSeconds }}
{{- end }}
